---
- name: Copy empty.sh
  copy: src=empty.sh dest=/empty.sh mode=755
  become: yes
  when: rerun | default(false) !=true

- name: Add cron job
  cron: name="Empty logstash.stdout" minute="0" job="/empty.sh"
  become: yes
  when: rerun | default(false) !=true
